### ISSUE TITLE
[winecord] a wine emulator running in discord

### ISSUE THREAD

**Issue by Celestemysterios** [nexpid/BunnyPlugins#107]
### Check all the boxes below

- [X] I have checked that this feature hasn't already been suggested

### Discord username

celestemyst

### Simple description

winlator in discord basically 
~~this is definitely not a troll suggestion though i would be surprised if you actually did it~~

### Elaborate

you run windows shit in discord/bunny

**Comment by nexpid** [comment]
crazy
