### ISSUE TITLE
Cloud Sync - Fails to decrypt txt file when trying to import the plugin list

### ISSUE THREAD

**Issue by I-794** [nexpid/BunnyPlugins#108]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

i_795

### Detailed Info

When i export the txt file of all of my current plugins, that is successful, but when i try to import them, it fails and gives me this message:
![IMG_6702](https://github.com/nexpid/BunnyPlugins/assets/147570875/3cfb0906-1393-46bc-8781-084229408396)

### Steps to Reproduce

1. Go to the Plugin info for Cloud sync
2. Export Local Data and enter the password
3. Click Import Local Data and enter decryption password.

### Bug Screenshot

![IMG_6702](https://github.com/nexpid/BunnyPlugins/assets/147570875/680dde41-564e-4ed4-84eb-5def5c0be50c)

### System Info

__System Information__

[**Device**]
> Device: iPhone11,8
> Model: iPhone
> Manufacturer: Apple Inc.
> Brand: iPhone
> Display: 828x1792
[**Hardware**]
> CPU Cores: 6
> Network: Cellular
[**Software**]
> OS: iOS
> Version: 17.5.1
[**Discord**]
> Branch: ptb
> Version: 230.0
> Build: 59343
> Vendetta: e9d80c7-main
> CPU Usage: 8.03%
> Memory Usage: 365 MB
[**React**]
> Version: 18.2.0
> Hermes Bytecode: 94
> Hermes: for RN 0.72.3
> Native: 0.72.3

**Comment by nexpid** [comment]
decryption, encryption & a major overhaul of Cloud Sync's API is coming soon:tm: so this will be closed when I finish it

**Comment by I-794** [comment]
> decryption, encryption & a major overhaul of Cloud Sync's API is coming soon:tm: so this will be closed when I finish it

When will that happen?

**Comment by nexpid** [comment]
> > decryption, encryption & a major overhaul of Cloud Sync's API is coming soon:tm: so this will be closed when I finish it
> 
> When will that happen?

now! it's available in the dev branch rn https://github.com/nexpid/BunnyPlugins/tree/dev/plugins/cloud-sync
https://dev.bunny.nexpid.xyz/cloud-sync
