### ISSUE TITLE
[TwemojiEverywhere] Unable to see the emojis

### ISSUE THREAD

**Issue by Ruyeex** [nexpid/BunnyPlugins#109]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@ruyeex

### Detailed Info

The plugin doesn't work with the fluency, mono emojis except with reactions and checking the emoji.

### Steps to Reproduce

1. Enable the plugin
2. Pick any emoji except the default one

### Crash Info

It doesn't have a crash issue

### Bug Screenshot

![Screenshot_20240622-223439](https://github.com/nexpid/BunnyPlugins/assets/99507424/32e945ce-89ca-4f24-ae7c-bbfaf2bc4e1d)
![Screenshot_20240622-231702](https://github.com/nexpid/BunnyPlugins/assets/99507424/fa557c40-4bad-4744-acf8-02f989f3d5a3)

### System Info

Device: Samsung SM-aA4005FN
Manufacturer: Samsung
Brand: Samsung

OS: Android
Version: 11

Discord Branch: googleRelease
Discord Version: 232.15
Discord Build: 232015
Vendetta Version: 39d80c7-main

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
emoji picker and chat are both native, meaning they can't be modified as easily as other UI. might try to fix this but don't count on anything
