### ISSUE TITLE
bug(nexxutils): `Send spotify invite link` feature doesn't work with recent new context menu change

### ISSUE THREAD

**Issue by Rairof** [nexpid/BunnyPlugins#65]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@rairof

### Detailed Info

`Send spotify invite link` button to replace Camara button doesn't work in the new upload context menu  alongside the Camara icon inside media context menu at first doesn't get replaced, this change was recently introduced in discord version 215.X so it's not a issue now but will be for future.

### Steps to Reproduce

N/A

### Crash Info

N/A

### Bug Screenshot

![Screenshot_20240203-105801](https://github.com/nexpid/VendettaPlugins/assets/107706560/bdc9dc10-7a73-4d0e-8b4d-069d08c26449)
![Screenshot_20240203-105851](https://github.com/nexpid/VendettaPlugins/assets/107706560/7b3d36ca-124b-4f44-ab2e-9ff728a4a76d)

### System Info

Device: Xiaomi 11T pro
Manufacturer: Xiaomi 
Brand: Xiaomi 

OS: Elixir OS
Version: A14

Discord Branch: canaryRelease
Discord Version: 216.8 
Discord Build: 216208
Vendetta Version: eed5355

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
fyi the two spotify modules will be moved to a seperate spotify plugin

**Comment by Rairof** [comment]
@nexpid can you also add option to hide the Camara tile when the Spotify invite link pill plugin is seperated from nexutils and it works over the now Polls pill?
![Screenshot_20240721-221635_Discord](https://github.com/user-attachments/assets/68b29e1e-f298-4c00-8f48-cea6e8353de5)
